export const site = {
  name: 'Next Tmpl',
  description: 'Next.js Starter Template with Modern Tech Stack (2025)',
  url: 'https://next-tmpl.mancuoj.me',
  author: 'Mancuoj',
  keywords: [
    'Next.js',
    'React',
    'TypeScript',
    'Next Tmpl',
    'Next 15',
    'React 19',
    'Next.js Starter',
    'Next.js Boilerplate',
    'Starter Template',
    'Tailwind CSS',
    'shadcn/ui',
    'Next-Auth',
    'Drizzle',
    'Turso',
    'SQLite',
    'Next-Intl',
    'i18n',
    'nuqs',
    'eslint',
    'jotai',
    'zustand',
  ],
}
