export const siteConfig = {
  author: 'mancuoj',
  name: 'Next Tmpl',
  description: 'Next.js Starter Template with Modern Tech Stack (2025)',
  origin: 'https://next-tmpl.mancuoj.me',
  og: 'https://next-tmpl.mancuoj.me/og.png',
  repo: 'https://github.com/mancuoj-collective/next-tmpl',
  keywords: [
    'Next.js 15',
    'React 19',
    'Tailwind CSS v4',
    'shadcn/ui',
    'Better Auth',
    'Drizzle ORM',
    'Turso DB',
    'SQLite',
    'TypeScript',
    'Next Tmpl',
    'Next.js Starter',
    'Next.js Boilerplate',
    'Starter Template',
    'nuqs',
    'eslint',
  ],
}
